org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 --illegal-access=permit --add-opens=java.base/java.io=ALL-UNNAMED
org.gradle.caching=true
# TODO: enable this once conventions plugin license processing is configuration cache friendly
org.gradle.configuration-cache=false
org.gradle.parallel=true
org.gradle.configureondemand=false
android.useAndroidX=true
android.injected.build.model.v2=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.native.ignoreDisabledTargets=true
kotlin.incremental.native=true
kotlin.native.parallelThreads=8
org.jetbrains.compose.experimental.jscanvas.enabled=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.enableKlibsCrossCompilation=false
compose.desktop.packaging.checkJdkVendor=false

