# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :android do
    lane :screenshots do
        build_android_app(
            task: 'assemble',
            build_type: 'Debug'
        )
        build_android_app(
            task: 'assemble',
            build_type: 'AndroidTest'
        )
        capture_android_screenshots(
            locales: ["en-US", "de-DE"],
            clear_previous_screenshots: true,
            skip_open_summary: true,
            use_timestamp_suffix: false,
            app_apk_path: "build/outputs/apk/androidTest/googlePlay/debug/Tammy-googlePlay-debug-androidTest.apk",
            tests_apk_path: "build/outputs/apk/googlePlay/debug/Tammy-googlePlay-debug.apk",
            device_type: "phone",
            specific_device: "emulator-5564"
        )
        capture_android_screenshots(
            locales: ["en-US", "de-DE"],
            clear_previous_screenshots: true,
            skip_open_summary: true,
            use_timestamp_suffix: false,
            app_apk_path: "build/outputs/apk/androidTest/googlePlay/debug/Tammy-googlePlay-debug-androidTest.apk",
            tests_apk_path: "build/outputs/apk/googlePlay/debug/Tammy-googlePlay-debug.apk",
            device_type: "sevenInch",
            specific_device: "emulator-5566"
        )
        capture_android_screenshots(
            locales: ["en-US", "de-DE"],
            clear_previous_screenshots: true,
            skip_open_summary: true,
            use_timestamp_suffix: false,
            app_apk_path: "build/outputs/apk/androidTest/googlePlay/debug/Tammy-googlePlay-debug-androidTest.apk",
            tests_apk_path: "build/outputs/apk/googlePlay/debug/Tammy-googlePlay-debug.apk",
            device_type: "tenInch",
            specific_device: "emulator-5568"
        )
    end

    lane :releaseBeta do
        upload_to_play_store(
            track: 'beta',
            skip_upload_apk: true,
            aab: "build/outputs/bundle/googlePlayRelease/Tammy-googlePlay-release.aab",
            version_code: ENV['CI_PIPELINE_IID']
        )
    end

    lane :release do
        upload_to_play_store(
            skip_upload_apk: true,
            aab: "build/outputs/bundle/googlePlayRelease/Tammy-googlePlay-release.aab",
            version_code: ENV['CI_PIPELINE_IID']
        )
    end
end

platform :ios do
    lane :beta do
        setup_ci(
            timeout: 1200, # 20 mins
            keychain_name: "ios_keychain"
        )
        sync_code_signing(
            type: "appstore",
            readonly: true,
            git_branch: "main",
            clone_branch_directly: true,
            keychain_name: "ios_keychain",
        )
        update_code_signing_settings(
              use_automatic_signing: false,
              path: "iosApp/iosApp.xcodeproj",
              team_id: "C6CHAMK5QZ",
              bundle_identifier: "de.connect2x.tammy",
              targets: "Tammy for iOS",
              code_sign_identity: "Apple Distribution",
              profile_name: "match AppStore de.connect2x.tammy",
        )
        marketing_version = File.read("../build/generatedSrc/version.txt")
        puts marketing_version
        build_number = ENV["CI_PIPELINE_IID"] || "1"
        build_app(project: "iosApp/iosApp.xcodeproj",
                  scheme: "Tammy for iOS",
                  export_method: "app-store",
                  configuration: "Release",
                  xcargs: "CURRENT_PROJECT_VERSION=" + build_number + " MARKETING_VERSION=" + marketing_version,
        )
        api_key = app_store_connect_api_key(
            key_id: "9C3783X4A3",
            issuer_id: "f263cb3c-525b-41a1-a247-69b0d501ecde",
            key_filepath: "AuthKey_9C3783X4A3.p8",
            duration: 1200, # optional (maximum 1200)
            in_house: false # optional but may be required if using match/sigh
        )
        upload_to_testflight(
            api_key: api_key,
            skip_submission: true,
            skip_waiting_for_build_processing: true,
            distribute_external: false,
        )
        deliver(
          submit_for_review: true,
          automatic_release: true,
          release_notes: { # we could make this a bit more sophisticated, but to do so automatically is a bit more work
            "en-US" => "Bug fixes and performance improvements.",
            "de-DE" => "Fehlerbehebungen und Leistungsverbesserungen."
          },
          force: true,
          precheck_include_in_app_purchases: false,
        )
    end
    lane :cleanup do
        delete_keychain(name: "ios_keychain")
    end
end

platform :ios do
    lane :screenshots do
        capture_screenshots(
            scheme: "Tammy Screenshots"
        )
    end
end
