# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    lane :screenshots do
        build_android_app(
            task: 'assemble',
            build_type: 'Debug'
        )
        build_android_app(
            task: 'assemble',
            build_type: 'AndroidTest'
        )
        capture_android_screenshots(
            locales: ["en-US", "de-DE"],
            clear_previous_screenshots: true,
            skip_open_summary: true,
            use_timestamp_suffix: false,
            app_apk_path: "build/outputs/apk/androidTest/googlePlay/debug/Tammy-googlePlay-debug-androidTest.apk",
            tests_apk_path: "build/outputs/apk/googlePlay/debug/Tammy-googlePlay-debug.apk",
            device_type: "phone",
            specific_device: "emulator-5564"
        )
        capture_android_screenshots(
            locales: ["en-US", "de-DE"],
            clear_previous_screenshots: true,
            skip_open_summary: true,
            use_timestamp_suffix: false,
            app_apk_path: "build/outputs/apk/androidTest/googlePlay/debug/Tammy-googlePlay-debug-androidTest.apk",
            tests_apk_path: "build/outputs/apk/googlePlay/debug/Tammy-googlePlay-debug.apk",
            device_type: "sevenInch",
            specific_device: "emulator-5566"
        )
        capture_android_screenshots(
            locales: ["en-US", "de-DE"],
            clear_previous_screenshots: true,
            skip_open_summary: true,
            use_timestamp_suffix: false,
            app_apk_path: "build/outputs/apk/androidTest/googlePlay/debug/Tammy-googlePlay-debug-androidTest.apk",
            tests_apk_path: "build/outputs/apk/googlePlay/debug/Tammy-googlePlay-debug.apk",
            device_type: "tenInch",
            specific_device: "emulator-5568"
        )
    end

    lane :releaseBeta do
        upload_to_play_store(
            track: 'beta',
            skip_upload_apk: true,
            aab: "build/outputs/bundle/googlePlayRelease/Tammy-googlePlay-release.aab",
            version_code: ENV['CI_PIPELINE_IID']
        )
    end

    lane :release do
        upload_to_play_store(
            skip_upload_apk: true,
            aab: "build/outputs/bundle/googlePlayRelease/Tammy-googlePlay-release.aab",
            version_code: ENV['CI_PIPELINE_IID']
        )
    end
end
